
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LoWD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class game
{

    public int game_id { get; set; }

    public int undermountain_flag { get; set; }

    public int skullport_flag { get; set; }

    public int plus_one_flag { get; set; }

    public int create_date { get; set; }

}

}
