
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LoWD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class game
{

    public bool? game_id { get; set; }

    public bool? undermountain_flag { get; set; }

    public bool? skullport_flag { get; set; }

    public bool? plus_one_flag { get; set; }

    public System.DateTime create_date { get; set; }

}

}
