
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LoWD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class game_played
{

    public int game_id { get; set; }

    public int user_id { get; set; }

    public int lord_id { get; set; }

    public int lord_pts { get; set; }

    public int corruption_pts { get; set; }

    public int gold_pts { get; set; }

    public int adv_pts { get; set; }

    public int quest_pts { get; set; }

    public int quest_qty { get; set; }

}

}
